/**
 * FREELANCE BD HUB — ADMIN GLOBAL SEO CONTROLLER
 * Manages default SEO meta (title, description, OG image).
 * Note: sitemap.xml is now auto-generated by a Cloudflare Pages Function
 * (see functions/sitemap.xml.js), so no manual regeneration is needed here.
 */

import { db, doc, getDoc, setDoc } from '/assets/js/firebase-init.js';
import { showToast } from '/assets/js/utils.js';

export async function initAdminSEO() {
  await loadSEOSettings();
  
  const form = document.getElementById('seo-form');
  if (form) {
    form.onsubmit = async (e) => {
      e.preventDefault();
      await saveSEOSettings();
    };
  }
}

async function loadSEOSettings() {
  try {
    const snap = await getDoc(doc(db, 'settings', 'fbh_site'));
    if (snap.exists()) {
      const data = snap.data();
      document.getElementById('seo-default-title').value = data.defaultSeoTitle || 'Freelance BD Hub — Learn. Build. Freelance.';
      document.getElementById('seo-default-desc').value = data.defaultSeoDescription || 'বাংলাদেশের ফ্রিল্যান্সার ও ডেভেলপারদের জন্য নির্ভরযোগ্য রিসোর্স ও ক্যারিয়ার গাইড।';
      document.getElementById('seo-og-image').value = data.ogImage || window.location.origin + '/assets/images/logo.svg';
    }
  } catch (e) {
    console.warn('[Admin SEO] Settings load fallback:', e);
  }
}

async function saveSEOSettings() {
  const defaultSeoTitle = document.getElementById('seo-default-title').value.trim();
  const defaultSeoDescription = document.getElementById('seo-default-desc').value.trim();
  const ogImage = document.getElementById('seo-og-image').value.trim();
  
  try {
    await setDoc(doc(db, 'settings', 'fbh_site'), {
      defaultSeoTitle,
      defaultSeoDescription,
      ogImage,
      updatedAt: new Date()
    }, { merge: true });
    
    showToast('গ্লোবাল এসইও সেটিংস সফলভাবে সংরক্ষিত হয়েছে!', 'success');
  } catch (err) {
    showToast('সংরক্ষণ ব্যর্থ হয়েছে: ' + err.message, 'error');
  }
}